{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "govnohub.fullname" . }}-postgresql
  labels:
    {{- include "govnohub.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.postgresql.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "govnohub.fullname" . }}-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "govnohub.fullname" . }}-postgresql
  template:
    metadata:
      labels:
        app: {{ include "govnohub.fullname" . }}-postgresql
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "govnohub.fullname" . }}-postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "govnohub.fullname" . }}-postgresql
spec:
  selector:
    app: {{ include "govnohub.fullname" . }}-postgresql
  ports:
    - port: 5432
{{- end }}
