apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "govnohub.fullname" . }}-git
spec:
  accessModes: [{{ .Values.git.accessMode | default "ReadWriteMany" }}]
  resources:
    requests:
      storage: {{ .Values.git.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "govnohub.fullname" . }}-artifacts
spec:
  accessModes: [{{ .Values.artifacts.accessMode | default "ReadWriteMany" }}]
  resources:
    requests:
      storage: {{ .Values.artifacts.storage }}
