{{- $services := list "api-server" "git-server" "webhook-service" "actions-controller" "search-indexer" -}}
{{- range $services }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "govnohub.fullname" $ }}-{{ . }}
  labels:
    {{- include "govnohub.labels" $ | nindent 4 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "govnohub.fullname" . }}-actions-runner
  namespace: {{ .Values.runner.namespace }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "govnohub.fullname" . }}-actions-runner
  namespace: {{ .Values.runner.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "govnohub.fullname" . }}-actions-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "govnohub.fullname" . }}-actions-runner
  apiGroup: rbac.authorization.k8s.io
